In [1]:
import pandas as pd
import numpy as np


In [13]:
dict1={'names':['ramesh','suresh','mahesh',np.nan],
       'age':[22,42,np.nan,22],
       'city':[np.nan,'latur','hyd','bng']}

       

In [15]:
data=pd.DataFrame(dict1)
data

names   age   city
0  ramesh  22.0    NaN
1  suresh  42.0  latur
2  mahesh   NaN    hyd
3     NaN  22.0    bng

In [17]:
data.to_csv('data1.csv',index=False)

**isnull**

In [19]:
data.isnull()

names    age   city
0  False  False   True
1  False  False  False
2  False   True  False
3   True  False  False

**dropna**

In [21]:
drop the null values data based on rows and columns

SyntaxError: invalid syntax (3348677537.py, line 1)

In [21]:
#i want to extract the data without null vaues
data.dropna()


names   age   city
1  suresh  42.0  latur

In [25]:
data.dropna()

names   age   city
1  suresh  42.0  latur

In [29]:
data.dropna(axis=1)


Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [86]:
dict1={'names':['ramesh','suresh','mahesh',np.nan],
       'age':[22,42,np.nan,22],
       'city':[np.nan,'latur','hyd','bng'],
       'company':['wipro','cod','nsin','dis']
      }
       

In [62]:
data1=pd.DataFrame(dict1)
data1

names   age   city company
0  ramesh  22.0    NaN   wipro
1  suresh  42.0  latur     cod
2  mahesh   NaN    hyd    nsin
3     NaN  22.0    bng     dis

**fillina**

In [32]:
data1.fillna(30)

names   age   city company
0  ramesh  22.0     30   wipro
1  suresh  42.0  latur     cod
2  mahesh  30.0    hyd    nsin
3      30  22.0    bng     dis

In [34]:
data1['names'].fillna('manish')

0    ramesh
1    suresh
2    mahesh
3    manish
Name: names, dtype: object

**draw back :filling with random values is not a good apparch**

to avoid the we have some method
bacfill
bfill
ffill
pad


**pad**

In [36]:
data1.fillna(method='pad')

C:\Users\91937\AppData\Local\Temp\ipykernel_18860\116358274.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1.fillna(method='pad')


names   age   city company
0  ramesh  22.0    NaN   wipro
1  suresh  42.0  latur     cod
2  mahesh  42.0    hyd    nsin
3  mahesh  22.0    bng     dis

**mean_median_mode**

In [39]:
age_mean=data1['age'].mean()
print('age_mean',age_mean)
data1['age'].fillna(age_mean)

age_mean 28.666666666666668


0    22.000000
1    42.000000
2    28.666667
3    22.000000
Name: age, dtype: float64

In [41]:
age_mode=data1['age'].mode()
data['age'].fillna(age_mode)

0    22.0
1    42.0
2     NaN
3    22.0
Name: age, dtype: float64

In [43]:
city_mode=data1['city'].mode()
data1['city'].fillna(city_mode)

0      bng
1    latur
2      hyd
3      bng
Name: city, dtype: object

In [45]:
city_mode

0      bng
1      hyd
2    latur
Name: city, dtype: object

In [47]:
city_mode.values[0]

'bng'

**impute class**

In [50]:
import numpy as np
from sklearn.impute import KNNImputer
x=[[1,2,np.nan,],[3,np.nan,3],[np.nan,60,5],[4,5,6]]
pd.DataFrame(x)

0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  4.0   5.0  6.0

In [114]:
import numpy as np
from sklearn.impute import KNNImputer
x=[[1,2,np.nan],[4,4,3],[3,4,2],[3,3,2]]
imputer= KNNImputer(n_neighbors=2,weights='uniform')
imputer.fit_transform(x)

array([[1., 2., 2.],
       [4., 4., 3.],
       [3., 4., 2.],
       [3., 3., 2.]])

In [112]:
import numpy as np
from sklearn.impute import KNNImputer
x=[[1,2,3],[4,4,3],[3,4,2],[3,3,2]]
imputer=KNNImputer(n_neighbors=2)
imputer.fit_transform(x)

array([[1., 2., 3.],
       [4., 4., 3.],
       [3., 4., 2.],
       [3., 3., 2.]])

In [58]:
import numpy as np
from sklearn.impute import KNNImputer
x=[[1,2,np.nan,],[3,np.nan,3],[np.nan,60,5],[4,5,6]]
imputer=KNNImputer(n_neighbors =2,weights='uniform')
imputer.fit_transform(x)

array([[ 1. ,  2. ,  4.5],
       [ 3. , 31. ,  3. ],
       [ 3.5, 60. ,  5. ],
       [ 4. ,  5. ,  6. ]])

In [56]:
import numpy as np
from sklearn.impute import KNNImputer
x=[[1,2,np.nan,],[3,np.nan,3],[np.nan,60,5],[4,5,6]]
imputer=KNNImputer(n_neighbors =2,weights='distance')
imputer.fit_transform(x)

array([[ 1.        ,  2.        ,  4.2       ],
       [ 3.        , 31.        ,  3.        ],
       [ 3.04890298, 60.        ,  5.        ],
       [ 4.        ,  5.        ,  6.        ]])